<x-editor.base>
    <x-slot:formId>postform</x-slot>
    <x-slot:editorContainerId>addEditorImgContainerId</x-slot>
    <x-slot:titleId>titleTextArea</x-slot>
    <x-slot:contentId>fullEditorTextArea</x-slot>
    <x-slot:bulletListModalBtnId>bulletListBtn</x-slot>
    <x-slot:orderedListModalBtnId>orderedListBtn</x-slot>
    <x-slot:inputImgId>inputImgAdd</x-slot>
    <x-slot:addImageBtnId>addImgAddBtn</x-slot>
    <x-slot:dropdownTagListId>dropdownAddTagList</x-slot>
    <x-slot:tagsContainerId>tagAddEditorContainer</x-slot>
    <x-slot:tagShowBtnId>tagAddEditorButton</x-slot>
    <x-slot:dropdownTagListCheckboxId>tagAddEditorCheckboxList</x-slot>
    <x-slot:submitTagBtnId>tagAddEditorSubmitBtn</x-slot>
    <x-slot:buttons>
        <button class='btn btn-light border border-0' id='cancelBtn'><i class='bi bi-x'></i></button>
    </x-slot>
    <x-slot:saveBtnId>submitBtn</x-slot>
</x-editor>